#DATABASE
spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/backend-service
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: on
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

server:
  port: 8081