#DATABASE
spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/backend-service?options=-c%20timezone=UTC
    username: ${DB_USERNAME:UNLOADED}
    password: ${DB_PASSWORD:UNLOADED}
  jpa:
    show-sql: on
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://localhost:8080

jwt:
  secret-key: ${JWT_SECRET_KEY}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    display-request-duration: true
  api-docs:
    path: /api-docs

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.results: TRACE